### ISSUE TITLE
Missing method to determine thinking time via client side

### ISSUE THREAD

**Issue by Drevanoorschot** [rhbvkleef/EC4P#9]
The requirements state the following: 

_The thinking time of the computer player (and thus the power of the artificial intelligence) should be a parameter that can be changed via the client TUI._

My suggestion is to add a mandatory parameter to the method `READY ` where the client gives an integer representing seconds of thinking time. Then when a game is created, the average of the two thinking times of both clients will be used as the actual thinking time of the AI. If this time expires, the server will notify the client that his thinking time has expired and to the other client that he has won because his opponent took too long to make a move.

Additionally we should probably think about a maximum size of the integer as complex ai's will probably fill in the integer limit to get as much time as possible. My suggestion would be a limit of 10 seconds, in the worst case scenario, a game would take (10 * 64) / 60 minutes which is a bit less than 17 minutes (In my opinion already quite long for a game).

**Comment by VriesDeRick** [comment]
>  The thinking time of the computer player (and thus the power of the artificial intelligence) should be a parameter that can be changed via the client TUI. 

As I understood the assignment, this only needs to be done client-side (so when you let an AI play for you), and doesn't need to be communicated between server/clients. @RemcodM, is that correct?

> Additionally we should probably think about a maximum size of the integer as complex ai's will probably fill in the integer limit to get as much time as possible. My suggestion would be a limit of 10 seconds, in the worst case scenario, a game would take (10 * 64) / 60 minutes which is a bit less than 17 minutes (In my opinion already quite long for a game).

That is a valid point, as there also isn't a set time-out value, which might be useful to have, although I think such a value should be discussed during a project-hour and not in a Github-issue where only some people might look.

**Comment by RemcodM** [comment]
The requirement already tells it all:
**The thinking time of the computer player (and thus the power of the artificial intelligence) should be a parameter that can be changed via the client TUI.**
Since the client connects to a server and the AI runs on the client, you should be able to set the thinking time of the client on the client side. The server has no knowledge of the AI, since it will just look like a client sending moves. That these moves come from an AI makes no difference here. Therefore, a protocol change should not be needed.
